PageLayoutExample:

<PageLayoutExample>:
    MainWidget:
    BoxLayoutExample:
    AnchorLayoutExample:
    GridLayoutExample:

<ScrollViewExample>:
    StackLayoutExample:
        size_hint:1,None
        height:self.minimum_height


<StackLayoutExample>:
    # left-right,top-bottom
    #orientation: "rl-bt"
    #lrtb
    #padding: ("20dp","20dp","20dp","20dp")
    #spacing: "20dp", "20dp"


#    Button:
#        text: "A"
#        size_hint:.4,.2
#    Button:
#        text: "B"
#        size_hint:.4,.2
#    Button:
#        text: "C"
#        size_hint:.4,.2



<GridLayoutExample@GridLayout>:
    # NEED to specify either "rows" and/or "cols"
    cols: 3
    Button:
        text: "A"
        size_hint:None,1
        width:"60dp"
    Button:
        text: "B"
        size_hint: .5,1
    BoxLayoutExample:

    Button:
        text: "D"
        size_hint:None,1
        width:"60dp"
    Button:
        text: "E"
        size_hint: .5,1
    Button:
        text: "F"

<AnchorLayoutExample>:
    # right, left, center
    anchor_x: "center"
    # bottom, top, center
    anchor_y: "top"
    BoxLayout:
        size_hint: .1,.1
        Button:
            text: "A"
        Button:
            text: "B"
<BoxLayoutExample>:
    orientation: "vertical"
    AnchorLayout:
        anchor_x: "center"
        anchor_y: "top"
        BoxLayout:
            size_hint: .1,.1
            Button:
                text: "A"
            Button:
                text: "B"

    Button:
        text: "B"
        #size: 100,"60dp"
        #size_hint: 1, None
        size:"100dp","60dp"
        size_hint: .8,None
        pos_hint: {"center_x":.5}
    BoxLayout:
        BoxLayout:
            spacing:"5dp"
            size:"80dp","100dp"
            size_hint:None,1
            orientation: "vertical"
            Button:
                text: "Stat"
                #size: "40dp","40dp"
                #size_hint:None,None
            Button:
                text: "Inv"
                #size: "40dp","40dp"
                #size_hint:None,.2
            Button:
                text: "Quests"
                #size: "40dp","40dp"
                #size_hint:None,.2
            Button:
                text: "COG"
                size: "40dp","40dp"
                size_hint:1,None
        ScrollView:
            
            StackLayoutExample:
                size_hint:1,None
                height:self.minimum_height



<MainWidget>:
    Button:
        text: "Hello"
        size: "100dp","80dp"
        pos: "200dp","300dp"
        color: 0,0,1,1

    Label:
        text: "Hello2"
        size: "100dp","80dp"
        pos: "200dp","300dp"
        color: 1,0,0,1
            