BoxLayoutExample:

<BoxLayoutExample>:
    orientation: "vertical"
    Label:
        text: "A"

    Button:
        text: "B"
        #size: 100,"60dp"
        #size_hint: 1, None
        size:"100dp","60dp"
        size_hint: .8,None
        pos_hint: {"center_x":.5}
    BoxLayout:
        BoxLayout:
            spacing:"5dp"
            size:"80dp","100dp"
            size_hint:None,1
            orientation: "vertical"
            Button:
                text: "Stat"
                #size: "40dp","40dp"
                #size_hint:None,None
            Button:
                text: "Inv"
                #size: "40dp","40dp"
                #size_hint:None,.2
            Button:
                text: "Quests"
                #size: "40dp","40dp"
                #size_hint:None,.2
            Button:
                text: "COG"
                size: "40dp","40dp"
                size_hint:1,None
        Button:
            text: "D"

<MainWidget>:
    Button:
        text: "Hello"
        size: "100dp","80dp"
        pos: "200dp","300dp"
        color: 0,0,1,1

    Label:
        text: "Hello2"
        size: "100dp","80dp"
        pos: "200dp","300dp"
        color: 1,0,0,1
            